general.import = [
#  "~/.config/alacritty/nord-theme.toml",
  "~/.config/alacritty/tokyonight-night.toml"
]

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

#[[keyboard.bindings]]
#chars = "\f"
#key = "K"
#mode = "~Vi|~Search"
#mods = "Control"

[[keyboard.bindings]]
key = "/"
mods = "Control|Shift"
action = "ReceiveChar"
[[keyboard.bindings]]
key = "f"
mods = "Control|Shift"
action = "ReceiveChar"

[scrolling]
"history" = 10000

[window]
decorations = "none"
opacity = 0.95
padding.x = 10

