---
commands:
  - name: FFMPEG Video Loopback
    cmd: gst-launch-1.0 v4l2src device=/dev/video0 ! tee name=t ! queue ! v4l2sink device=/dev/video10 t. ! queue ! v4l2sink device=/dev/video11
    showLog: true
