Threshold = 95
DisplayMonitorSources = true
EnableUpdates = true
GuiltTripped = false
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_input.usb-Razer_Inc_Razer_Kiyo_Pro-02.analog-stereo"
LastUsedOutput = ""
