Threshold = 95
DisplayMonitorSources = false
EnableUpdates = true
GuiltTripped = false
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_input.usb-Sonix_Technology_Co.__Ltd._Webcam_1080P_HDR_SN0001-03.analog-stereo"
LastUsedOutput = ""
